language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

# safelist
branches:
  only:
  - master
  - ArtBy-Hotfix

cache:
  directories:
    - node_modules

script:
  - npm run build:devgit
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./spacesnstories/
  on:
    branch: master