export const country = [
     "Andorra",
     "United Arab Emirates",
    "Afghanistan",
    "Antigua and Barbuda",
    "Anguilla",
    "Albania",
    "Armenia",
    "Angola",
    "Antarctica",
    "Argentina",
    "American Samoa",
    "Austria",
    "Australia",
    "Aruba",
    "Aland Islands",
    "Azerbaijan",
    "Bosnia and Herzegovina",
    "Barbados",
    "Bangladesh",
    "Belgium",
    "Burkina Faso",
    "Bulgaria",
    "Bahrain",
    "Burundi",
    "Benin",
    "Saint Barthelemy",
    "Bermuda",
    "Brunei",
    "Bolivia",
    "Bonaire, Saint Eustatius and Saba",
    "Brazil",
    "Bahamas",
    "Bhutan",
    "Bouvet Island",
    "Botswana",
    "Belarus",
    "Belize",
    "Canada",
    "Cocos Islands",
    "Democratic Republic of the Congo",
    "Central African Republic",
    "Republic of the Congo",
    "Switzerland",
    "Ivory Coast",
    "Cook Islands",
    "Chile",
    "Cameroon",
    "China",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Cape Verde",
    "Curacao",
    "Christmas Island",
    "Cyprus",
    "Czech Republic",
    "Germany",
    "Djibouti",
    "Denmark",
    "Dominica",
    "Dominican Republic",
    "Algeria",
    "Ecuador",
    "Estonia",
    "Egypt",
    "Western Sahara",
    "Eritrea",
    "Spain",
    "Ethiopia",
    "Finland",
    "Fiji",
    "Falkland Islands",
    "Micronesia",
    "Faroe Islands",
    "France",
    "Gabon",
    "United Kingdom",
    "Grenada",
    "Georgia",
    "French Guiana",
    "Guernsey",
    "Ghana",
    "Gibraltar",
    "Greenland",
    "Gambia",
    "Guinea",
    "Guadeloupe",
    "Equatorial Guinea",
    "Greece",
    "South Georgia and the South Sandwich Islands",
    "Guatemala",
    "Guam",
    "Guinea-Bissau",
    "Guyana",
    "Hong Kong",
    "Honduras",
    "Croatia",
    "Haiti",
    "Hungary",
    "Indonesia",
    "Ireland",
    "Israel",
    "Isle of Man",
    "India",
    "British Indian Ocean Territory",
    "Iraq",
    "Iran",
    "Iceland",
    "Italy",
    "Jersey",
    "Jamaica",
    "Jordan",
    "Japan",
    "Kenya",
    "Kyrgyzstan",
    "Cambodia",
    "Kiribati",
    "Comoros",
    "Saint Kitts and Nevis",
    "North Korea",
    "South Korea",
    "Kuwait",
    "Cayman Islands",
    "Kazakhstan",
    "Laos",
    "Lebanon",
    "Saint Lucia",
    "Liechtenstein",
    "Sri Lanka",
    "Liberia",
    "Lesotho",
    "Lithuania",
    "Luxembourg",
    "Latvia",
    "Libya",
    "Morocco",
    "Monaco",
    "Moldova",
    "Montenegro",
    "Saint Martin",
    "Madagascar",
    "Marshall Islands",
    "Macedonia",
    "Mali",
    "Myanmar",
    "Mongolia",
    "Macao",
    "Northern Mariana Islands",
    "Martinique",
    "Mauritania",
    "Montserrat",
    "Malta",
    "Mauritius",
    "Maldives",
    "Malawi",
    "Mexico",
    "Malaysia",
    "Mozambique",
    "Namibia",
    "New Caledonia",
    "Niger",
    "Norfolk Island",
    "Nigeria",
    "Nicaragua",
    "Netherlands",
    "Norway",
    "Nepal",
    "Nauru",
    "Niue",
    "New Zealand",
    "Oman",
    "Panama",
    "Peru",
    "French Polynesia",
    "Papua New Guinea",
    "Philippines",
    "Pakistan",
    "Poland",
    "Saint Pierre and Miquelon",
    "Pitcairn",
    "Puerto Rico",
    "Palestinian Territory",
    "Portugal",
    "Palau",
    "Paraguay",
    "Qatar",
    "Reunion",
    "Romania",
    "Serbia",
    "Russia",
    "Rwanda",
    "Saudi Arabia",
    "Solomon Islands",
    "Seychelles",
    "Sudan",
    "Sweden",
    "Singapore",
    "Saint Helena",
    "Slovenia",
    "Svalbard and Jan Mayen",
    "Slovakia",
    "Sierra Leone",
    "San Marino",
    "Senegal",
    "Somalia",
    "Suriname",
    "South Sudan",
    "Sao Tome and Principe",
    "El Salvador",
    "Sint Maarten",
    "Syria",
    "Swaziland",
    "Turks and Caicos Islands",
    "Chad",
    "Togo",
    "Thailand",
    "Tajikistan",
    "Tokelau",
    "East Timor",
    "Turkmenistan",
    "Tunisia",
    "Tonga",
    "Turkey",
    "Trinidad and Tobago",
    "Tuvalu",
    "Taiwan",
    "Tanzania",
    "Ukraine",
    "Uganda",
    "United States Minor Outlying Islands",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vatican",
    "Saint Vincent and the Grenadines",
    "Venezuela",
    "British Virgin Islands",
    "U.S. Virgin Islands",
    "Vietnam",
    "Vanuatu",
    "Wallis and Futuna",
    "Samoa",
    "Kosovo",
    "Yemen",
    "Mayotte",
    "South Africa",
    "Zambia",
    "Zimbabwe"
];
export const countryCodes = {
    "Andorra": "+376",
    "United Arab Emirates": "+971",
    "Afghanistan": "+93",
    "Antigua and Barbuda": "+1-268",
    "Anguilla": "+1-264",
    "Albania": "+355",
    "Armenia": "+374",
    "Angola": "+244",
    "Antarctica": "+672",
    "Argentina": "+54",
    "American Samoa": "+1-684",
    "Austria": "+43",
    "Australia": "+61",
    "Aruba": "+297",
    "Aland Islands": "+358-18",
    "Azerbaijan": "994",
    "Bosnia and Herzegovina": "+387",
    "Barbados": "+1-246",
    "Bangladesh": "+880",
    "Belgium": "+32",
    "Burkina Faso": "+226",
    "Bulgaria": "+359",
    "Bahrain": "+973",
    "Burundi": "+257",
    "Benin": "+229",
    "Saint Barthelemy": "+590",
    "Bermuda": "+1-441",
    "Brunei": "+673",
    "Bolivia": "+591",
    "Bonaire, Saint Eustatius and Saba": "+599",
    "Brazil": "+55",
    "Bahamas": "+1-242",
    "Bhutan": "+975",
    "Bouvet Island": "+47",
    "Botswana": "+267",
    "Belarus": "+375",
    "Belize": "+501",
    "Canada": "+1",
    "Cocos Islands": "+61",
    "Democratic Republic of the Cong": "+243",
    "Central African Republic": "+236",
    "Republic of the Congo": "+242",
    "Switzerland": "+41",
    "Ivory Coast": "+225",
    "Cook Islands": "+682",
    "Chile": "+56",
    "Cameroon": "+237",
    "China": "+86",
    "Colombia": "+57",
    "Costa Rica": "+506",
    "Cuba": "+53",
    "Cape Verde": "+238",
    "Curacao": "+599",
    "Christmas Island": "+61",
    "Cyprus": "+357",
    "Czech Republic": "+420",
    "Germany": "+49",
    "Djibouti": "+253",
    "Denmark": "+45",
    "Dominica": "+1-767",
    "Dominican Republic": "+1-809",
    "Algeria": "+213",
    "Ecuador": "+593",
    "Estonia": "+372",
    "Egypt": "+20",
    "Western Sahara": "+212",
    "Eritrea": "+291",
    "Spain": "+34",
    "Ethiopia": "+251",
    "Finland": "+358",
    "Fiji": "+679",
    "Falkland Islands": "+500",
    "Micronesia": "+691",
    "Faroe Islands": "+298",
    "France": "+33",
    "Gabon": "+241",
    "United Kingdom": "+44",
    "Grenada": "+1-473",
    "Georgia": "+995",
    "French Guiana": "+594",
    "Guernsey": "+44-1481",
    "Ghana": "+233",
    "Gibraltar": "+350",
    "Greenland": "+299",
    "Gambia": "+220",
    "Guinea": "+224",
    "Guadeloupe": "+590",
    "Equatorial Guinea": "+240",
    "Greece": "+30",
    "South Georgia and the South Sandwich Islands": "+500",
    "Guatemala": "+502",
    "Guam": "+1-671",
    "Guinea-Bissau": "+245",
    "Guyana": "+592",
    "Hong Kong": "+852",
    "Honduras": "+504",
    "Croatia": "+385",
    "Haiti": "+509",
    "Hungary": "+36",
    "Indonesia": "+62",
    "Ireland": "+353",
    "Israel": "+972",
    "Isle of Man": "+44-1624",
    "India": "+91",
    "British Indian Ocean Territory": "+246",
    "Iraq": "+964",
    "Iran": "+98",
    "Iceland": "+354",
    "Italy": "+39",
    "Jersey": "+44-1534",
    "Jamaica": "+1-876",
    "Jordan": "+962",
    "Japan": "+81",
    "Kenya": "+254",
    "Kyrgyzstan": "+996",
    "Cambodia": "+855",
    "Kiribati": "+686",
    "Comoros": "+269",
    "Saint Kitts and Nevis": "+1-869",
    "North Korea": "+850",
    "South Korea": "+82",
    "Kuwait": "+965",
    "Cayman Islands": "+1-345",
    "Kazakhstan": "+7",
    "Laos": "+856",
    "Lebanon": "+961",
    "Saint Lucia": "+1-758",
    "Liechtenstein": "+423",
    "Sri Lanka": "+94",
    "Liberia": "+231",
    "Lesotho": "+266",
    "Lithuania": "+370",
    "Luxembourg": "+352",
    "Latvia": "+371",
    "Libya": "+218",
    "Morocco": "+212",
    "Monaco": "+377",
    "Moldova": "+373",
    "Montenegro": "+382",
    "Saint Martin": "+590",
    "Madagascar": "+261",
    "Marshall Islands": "+692",
    "Macedonia": "+389",
    "Mali": "+223",
    "Myanmar": "+95",
    "Mongolia": "+976",
    "Macao": "+853",
    "Northern Mariana Islands": "+1-670",
    "Martinique": "+596",
    "Mauritania": "+222",
    "Montserrat": "+1-664",
    "Malta": "+356",
    "MMauritiusU": "+230",
    "Maldives": "+960",
    "Malawi": "+265",
    "Mexico": "+52",
    "Malaysia": "+60",
    "Mozambique": "+258",
    "Namibia": "+264",
    "New Caledonia": "+687",
    "Niger": "+227",
    "Norfolk Island": "+672",
    "Nigeria": "+234",
    "Nicaragua": "+505",
    "Netherlands": "+31",
    "Norway": "+47",
    "Nepal": "+977",
    "Nauru": "+674",
    "Niue": "+683",
    "New Zealand": "+64",
    "Oman": "+968",
    "Panama": "+507",
    "Peru": "+51",
    "French Polynesia": "+689",
    "Papua New Guinea": "+675",
    "Philippines": "+63",
    "Pakistan": "+92",
    "Poland": "+48",
    "Saint Pierre and Miquelon": "+508",
    "Pitcairn": "+870",
    "Puerto Rico": "+1-787 & 1-939",
    "Palestinian Territory": "+970",
    "Portugal": "+351",
    "Palau": "+680",
    "Paraguay": "+595",
    "Qatar": "+974",
    "Reunion": "+262",
    "Romania": "+40",
    "Serbia": "+381",
    "Russia": "+7",
    "Rwanda": "+250",
    "Saudi Arabia": "+966",
    "Solomon Islands": "+677",
    "Seychelles": "+248",
    "Sudan": "+249",
    "Sweden": "+46",
    "Singapore": "+65",
    "Saint Helena": "+290",
    "Slovenia": "+386",
    "Svalbard and Jan Mayen": "+47",
    "Slovakia": "+421",
    "Sierra Leone": "+232",
    "San Marino": "+378",
    "Senegal": "+221",
    "Somalia": "+252",
    "Suriname": "+597",
    "South Sudan": "+211",
    "Sao Tome and Principe": "+239",
    "El Salvador": "+503",
    "Sint Maarten": "+599",
    "Syria": "+963",
    "Swaziland": "+268",
    "Turks and Caicos Islands": "+1-649",
    "Chad": "+235",
    "Togo": "+228",
    "Thailand": "+66",
    "Tajikistan": "+992",
    "Tokelau": "+690",
    "East Timor": "+670",
    "Turkmenistan": "+993",
    "Tunisia": "+216",
    "Tonga": "+676",
    "Turkey": "+90",
    "Trinidad and Tobago": "+1-868",
    "Tuvalu": "+688",
    "Taiwan": "+886",
    "Tanzania": "+255",
    "Ukraine": "+380",
    "Uganda": "+256",
    "United States Minor Outlying Islands": "+1",
    "United States": "+1",
    "Uruguay": "+598",
    "Uzbekistan": "+998",
    "Vatican": "+379",
    "Saint Vincent and the Grenadines": "+1-784",
    "Venezuela": "+58",
    "British Virgin Islands": "+1-284",
    "U.S. Virgin Islands": "+1-340",
    "Vietnam": "+84",
    "Vanuatu": "+678",
    "Wallis and Futuna": "+681",
    "Samoa": "+685",
    "Kosovo": "+383",
    "Yemen": "+967",
    "Mayotte": "+262",
    "South Africa": "+27",
    "Zambia": "+260",
    "Zimbabwe": "+263"
}
